app = "lofi-green-eyes"
primary_region = "ord"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
gpu_kind = "a100-pcie-40gb"
